<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>13.0</LangVersion>
		<Nullable>enable</Nullable>
		<SelfContained>true</SelfContained>
		<PublishTrimmed>false</PublishTrimmed>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishAot>false</PublishAot>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<ApplicationIcon>Assets\logo.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\logo.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AFSLib" Version="1.1.2" />
		<PackageReference Include="Avalonia" Version="12.1.0" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
		<PackageReference Include="HeroesONE-R" Version="1.0.0" />
		<PackageReference Include="PanAndZoom" Version="12.0.0.1" />
		<PackageReference Include="ShadowFNT" Version="2.0.1" />
		<PackageReference Include="SkiaSharp" Version="4.150.1" />
		<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.150.1" />
		<PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Submodules\ShadowSET\ShadowSET\ShadowSET.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Views\MainWindow.axaml.cs">
			<DependentUpon>MainWindow.axaml</DependentUpon>
			<SubType>Code</SubType>
		</Compile>
	</ItemGroup>
</Project>
